"""Add provider field to tasks table

Revision ID: 1408c59b0b41
Revises: 8479ad8b8fea
Create Date: 2025-11-26 16:37:44.392102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1408c59b0b41'
down_revision: Union[str, Sequence[str], None] = '8479ad8b8fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('provider', sa.String(length=50), nullable=True))
    op.alter_column('tasks', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('tasks', 'provider')
    # ### end Alembic commands ###
